version: '3.8'
services: 
    main:
        build: 
            context: ./my_app
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - ./my_app:/app
        ports:
            - 8001:8000
    queue:
        build: 
            context: ./my_app
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on: 
            - db        

    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: laravel
            MYSQL_ROOT: root
            MYSQL_PASSWORD: root
       
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3307:3306